package com.sl2425.da.sellersapp.restapi.model.codeStatus;

public enum SellerProductCodeStatus
{
    SELLER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    SUCCESS,
    SELLER_PRODUCT_ALREADY_EXISTS,
    SELLER_PRODUCT_NOT_FOUND,
    INVALID_REQUEST_TYPE,
    SELLER_PRODUCT_IS_NULL,
    PRICE_NOT_VALID,
    STOCK_NOT_VALID,
    DATE_PERIOD_COLLISION,
    DATE_PERIOD_NOT_NULL,
    OFFER_PRICE_NOT_VALID,
    OFFER_PRICE_NOT_NULL,
    DATE_PERIOD_NULL,
    OFFER_PRICE_NULL,
    DATE_PERIOD_NOT_PRESENT_OR_FUTURE,
    DATE_PERIOD_NOT_AVAILABLE,
    OFFER_PRICE_NOT_WITHIN_RANGE,
    DATE_PERIOD_TOO_LONG,
    OFFER_PRICE_TOO_HIGH,
    OFFER_HAS_NOT_ENDED,

}
