openapi: "3.1.0"
info:
  title: "FinalActivitySellersApp API"
  description: "API for managing sellers in the FinalActivitySellersApp"
  version: "1.0.0"
servers:
  - url: "https://FinalActivitySellersApp"
paths:
  /api/sellers:
    get:
      summary: "Returns a Seller object"
      description: "Accepts CIF and password in the request body and returns the seller's information if authenticated successfully."
      operationId: "getSellerByCifAndPassword"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SellerLoginDTO"
            example:
              cif: "A12345678"
              password: "password123"
        required: true
      responses:
        "200":
          description: "Successful authentication and seller data retrieval"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SellerEntity"
        "400":
          description: "Invalid CIF or password"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
                example:
                  message: "Incorrect password"
                  code: "INCORRECT_PASSWORD"
        "404":
          description: "CIF not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
                example:
                  message: "CIF not found"
                  code: "CIF_NOT_FOUND"
    put:
      summary: "Updates Seller Information"
      description: "Updates the information of an existing seller using the provided CIF and returns whenever the update was successful or not and information about the error"
      operationId: "updateSeller"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SellerUpdateDTO"
            example:
              id: 1
              cif: "A12345678"
              name: "John Updated"
              businessName: "John's Updated Business"
              phone: "987654321"
              email: "updated@test.com"
              url: "https://www.updated.com"
              newPassword: "newpassword123"
              confirmNewPassword: "newpassword123"
        required: true
      responses:
        "200":
          description: "Seller updated successfully"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "Seller updated successfully."
        "400":
          description: "Invalid update data or validation errors"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
                example:
                  message: "Seller update failed."
                  errors:
                    - "PASSWORDS_DO_NOT_MATCH"
                    - "INVALID_EMAIL_FORMAT"
        "404":
          description: "Seller not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
                example:
                  message: "Seller not found"
                  code: "SELLER_NOT_FOUND"

components:
  schemas:
    SellerLoginDTO:
      type: "object"
      properties:
        cif:
          type: "string"
          description: "Unique identifier for the seller"
        password:
          type: "string"
          description: "Seller's password"
      required:
        - cif
        - password
        - name
    SellerUpdateDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
          description: "Unique identifier of the seller"
        cif:
          type: "string"
          description: "Unique identifier for the seller"
        name:
          type: "string"
          description: "Name of the seller"
        businessName:
          type: "string"
          description: "Business name of the seller"
        phone:
          type: "string"
          description: "Contact phone number"
        email:
          type: "string"
          description: "Contact email address"
        url:
          type: "string"
          description: "Website URL"
        newPassword:
          type: "string"
          description: "New password for the seller"
        confirmNewPassword:
          type: "string"
          description: "Confirmation of the new password"
      required:
        - cif
        - name
    SellerEntity:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        cif:
          type: "string"
        name:
          type: "string"
        businessName:
          type: "string"
        phone:
          type: "string"
        email:
          type: "string"
        url:
          type: "string"
        password:
          type: "string"
    ErrorResponse:
      type: "object"
      properties:
        message:
          type: "string"
          description: "Error message"
        code:
          type: "string"
          description: "Error code for internal reference"
        errors:
          type: "array"
          items:
            type: "string"
          description: "List of validation errors"
